# Generated by Django 4.2.5 on 2023-10-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='pdf_file',
            new_name='txt_file',
        ),
    ]
