# Generated by Django 4.2.5 on 2023-10-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to='chat_data/')),
                ('openai_api_key', models.CharField(max_length=100)),
            ],
        ),
    ]
